remote_theme: just-the-docs/just-the-docs
title: Botany/PlantPath 563
exclude:
   - README.md
   - PP875/
   - data/
   - lecture-notes/lecture1.md
   - lecture-notes/lecture2.md
   - lecture-notes/lecture4.md
   - lecture-notes/lecture6.md
aux_links:
  "Materials on GitHub":
    - "//github.com/crsl4/phylogenetics-class"
footer_content: "Copyright Solis-Lemus lab &copy; 2022. Distributed by an <a href=\"https://github.com/crsl4/phylogenetics-class/tree/master/LICENSE\">MIT license.</a>"
callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
compress_html:
  blanklines: true
# LaTeX rendering via "katex" (KaTeX, default) or "mathjax" (MathJax) or "none" / "off" (NO rendering)
# https://github.com/just-the-docs/just-the-docs/issues/198
latex: katex